const data = {
  cinema_list: [
    {
      CinemaId: 1,
      CinemaName: "Junction City Cinema",
    },
    {
      CinemaId: 2,
      CinemaName: "Mingalar Cinema",
    },
    {
      CinemaId: 3,
      CinemaName: "Junction Square Cinema",
    },
  ],
  cinema_room: [
    {
      RoomId: 1,
      CinemaId: 1,
      RoomNumber: 1,
      RoomName: "Cinema Ι",
    },
    {
      RoomId: 2,
      CinemaId: 2,
      RoomNumber: 1,
      RoomName: "Cinema Ι",
    },
    {
      RoomId: 3,
      CinemaId: 3,
      RoomNumber: 1,
      RoomName: "Cinema Ι",
    },
    {
      RoomId: 4,
      CinemaId: 3,
      RoomNumber: 2,
      RoomName: "Cinema ΙI",
      SeatingCapacity: 0,
    },
  ],
  movie_lists: [
    {
      MovieId: 1,
      MovieTitle: "Tom and Jerry",
      MoviePhoto: "/images/tom_and_jerry.jpg",
    },
    {
      MovieId: 2,
      MovieTitle: "Pokémon: Detective Pikachu",
      MoviePhoto: "/images/pokemon.jpg",
    },
    {
      MovieId: 3,
      MovieTitle: "Spider-Man: Across the Spider-Verse",
      MoviePhoto: "/images/spider_man.jpg",
    },
    {
      MovieId: 1,
      MovieTitle: "Tom and Jerry",
      MoviePhoto: "/images/tom_and_jerry.jpg",
    },
    {
      MovieId: 2,
      MovieTitle: "Pokémon: Detective Pikachu",
      MoviePhoto: "/images/pokemon.jpg",
    },
    {
      MovieId: 3,
      MovieTitle: "Spider-Man: Across the Spider-Verse",
      MoviePhoto: "/images/spider_man.jpg",
    },
    {
      MovieId: 1,
      MovieTitle: "Tom and Jerry",
      MoviePhoto: "/images/tom_and_jerry.jpg",
    },
    {
      MovieId: 2,
      MovieTitle: "Pokémon: Detective Pikachu",
      MoviePhoto: "/images/pokemon.jpg",
    },
    {
      MovieId: 3,
      MovieTitle: "Spider-Man: Across the Spider-Verse",
      MoviePhoto: "/images/spider_man.jpg",
    },
  ],
  seat_lists: [
    {
      SeatId: 1,
      RoomId: 1,
      SeatNo: 1,
      RowName: "A",
      SeatType: "single",
    },
    {
      SeatId: 2,
      RoomId: 1,
      SeatNo: 2,
      RowName: "A",
      SeatType: "single",
    },
    {
      SeatId: 3,
      RoomId: 1,
      SeatNo: 3,
      RowName: "A",
      SeatType: "single",
    },
    {
      SeatId: 4,
      RoomId: 1,
      SeatNo: 4,
      RowName: "A",
      SeatType: "single",
    },
    {
      SeatId: 5,
      RoomId: 1,
      SeatNo: 5,
      RowName: "A",
      SeatType: "single",
    },
    {
      SeatId: 1,
      RoomId: 1,
      SeatNo: 1,
      RowName: "B",
      SeatType: "single",
    },
    {
      SeatId: 2,
      RoomId: 1,
      SeatNo: 2,
      RowName: "B",
      SeatType: "single",
    },
    {
      SeatId: 3,
      RoomId: 1,
      SeatNo: 3,
      RowName: "B",
      SeatType: "single",
    },
    {
      SeatId: 4,
      RoomId: 1,
      SeatNo: 4,
      RowName: "B",
      SeatType: "single",
    },
    {
      SeatId: 5,
      RoomId: 1,
      SeatNo: 5,
      RowName: "B",
      SeatType: "single",
    },
    {
      SeatId: 1,
      RoomId: 1,
      SeatNo: 1,
      RowName: "C",
      SeatType: "single",
    },
    {
      SeatId: 2,
      RoomId: 1,
      SeatNo: 2,
      RowName: "C",
      SeatType: "single",
    },
    {
      SeatId: 3,
      RoomId: 1,
      SeatNo: 3,
      RowName: "C",
      SeatType: "single",
    },
    {
      SeatId: 4,
      RoomId: 1,
      SeatNo: 4,
      RowName: "C",
      SeatType: "single",
    },
    {
      SeatId: 5,
      RoomId: 1,
      SeatNo: 5,
      RowName: "C",
      SeatType: "single",
    },
    {
      SeatId: 1,
      RoomId: 1,
      SeatNo: 1,
      RowName: "D",
      SeatType: "single",
    },
    {
      SeatId: 2,
      RoomId: 1,
      SeatNo: 2,
      RowName: "D",
      SeatType: "single",
    },
    {
      SeatId: 3,
      RoomId: 1,
      SeatNo: 3,
      RowName: "D",
      SeatType: "single",
    },
    {
      SeatId: 4,
      RoomId: 1,
      SeatNo: 4,
      RowName: "D",
      SeatType: "single",
    },
    {
      SeatId: 5,
      RoomId: 1,
      SeatNo: 5,
      RowName: "D",
      SeatType: "single",
    },
    {
      SeatId: 1,
      RoomId: 1,
      SeatNo: 1,
      RowName: "E",
      SeatType: "single",
    },
    {
      SeatId: 2,
      RoomId: 1,
      SeatNo: 2,
      RowName: "E",
      SeatType: "single",
    },
    {
      SeatId: 3,
      RoomId: 1,
      SeatNo: 3,
      RowName: "E",
      SeatType: "single",
    },
    {
      SeatId: 4,
      RoomId: 1,
      SeatNo: 4,
      RowName: "E",
      SeatType: "single",
    },
    {
      SeatId: 5,
      RoomId: 1,
      SeatNo: 5,
      RowName: "E",
      SeatType: "single",
    },
    {
      SeatId: 1,
      RoomId: 1,
      SeatNo: 1,
      RowName: "F",
      SeatType: "dual",
    },
    {
      SeatId: 2,
      RoomId: 1,
      SeatNo: 2,
      RowName: "F",
      SeatType: "dual",
    },
  ],
  movie_show_date: [
    {
      ShowDateId: 1,
      CinemaId: 1,
      RoomId: 1,
      MovieId: 1,
    },
    {
      ShowDateId: 2,
      CinemaId: 1,
      RoomId: 1,
      MovieId: 2,
    },
    {
      ShowDateId: 3,
      CinemaId: 1,
      RoomId: 1,
      MovieId: 3,
    },
    {
      ShowDateId: 1,
      CinemaId: 2,
      RoomId: 2,
      MovieId: 1,
    },
    {
      ShowDateId: 2,
      CinemaId: 2,
      RoomId: 2,
      MovieId: 2,
    },
    {
      ShowDateId: 3,
      CinemaId: 2,
      RoomId: 2,
      MovieId: 3,
    },
    {
      ShowDateId: 1,
      CinemaId: 3,
      RoomId: 3,
      MovieId: 1,
    },
    {
      ShowDateId: 1,
      CinemaId: 3,
      RoomId: 4,
      MovieId: 1,
    },
    {
      ShowDateId: 2,
      CinemaId: 3,
      RoomId: 3,
      MovieId: 2,
    },
    {
      ShowDateId: 2,
      CinemaId: 3,
      RoomId: 4,
      MovieId: 2,
    },
    {
      ShowDateId: 3,
      CinemaId: 3,
      RoomId: 3,
      MovieId: 3,
    },
    {
      ShowDateId: 3,
      CinemaId: 3,
      RoomId: 4,
      MovieId: 3,
    },
    {
      ShowDateId: 4,
      CinemaId: 3,
      RoomId: 4,
      MovieId: 3,
    },
  ],
  movie_show_schedule: [
    {
      ShowId: 1,
      ShowDateId: 1,
      ShowDate: "2023-01-22",
      ShowTime: "09:00:00",
    },
    {
      ShowId: 2,
      ShowDateId: 1,
      ShowDate: "2023-01-22",
      ShowTime: "13:00:00",
    },
    {
      ShowId: 3,
      ShowDateId: 2,
      ShowDate: "2023-01-23",
      ShowTime: "09:00:00",
    },
    {
      ShowId: 4,
      ShowDateId: 2,
      ShowDate: "2023-01-23",
      ShowTime: "13:00:00",
    },
    {
      ShowId: 5,
      ShowDateId: 3,
      ShowDate: "2023-01-24",
      ShowTime: "13:00:00",
    },
    {
      ShowId: 6,
      ShowDateId: 3,
      ShowDate: "2023-01-24",
      ShowTime: "17:00:00",
    },
    {
      ShowId: 7,
      ShowDateId: 4,
      ShowDate: "2023-01-25",
      ShowTime: "15:00:00",
    },
    {
      ShowId: 8,
      ShowDateId: 4,
      ShowDate: "2023-01-25",
      ShowTime: "18:00:00",
    },
    {
      ShowId: 9,
      ShowDateId: 4,
      ShowDate: "2023-01-25",
      ShowTime: "20:00:00",
    },
    {
      ShowId: 10,
      ShowDateId: 5,
      ShowDate: "2023-01-26",
      ShowTime: "13:00:00",
    },
    {
      ShowId: 11,
      ShowDateId: 5,
      ShowDate: "2023-01-26",
      ShowTime: "18:00:00",
    },
  ],
  seat_price: [
    {
      SeatPriceId: 1,
      RoomId: 1,
      RowName: "A",
      SeatPrice: "5000",
    },

    {
      SeatPriceId: 2,
      RoomId: 1,
      RowName: "B",
      SeatPrice: "6000",
    },
    {
      SeatPriceId: 3,
      RoomId: 1,
      RowName: "C",
      SeatPrice: "7000",
    },
    {
      SeatPriceId: 4,
      RoomId: 1,
      RowName: "D",
      SeatPrice: "8000",
    },
    {
      SeatPriceId: 5,
      RoomId: 1,
      RowName: "E",
      SeatPrice: "9000",
    },
    {
      SeatPriceId: 6,
      RoomId: 1,
      RowName: "F",
      SeatPrice: "10000",
    },
    {
      SeatPriceId: 7,
      RoomId: 2,
      RowName: "A",
      SeatPrice: "5500",
    },

    {
      SeatPriceId: 8,
      RoomId: 2,
      RowName: "B",
      SeatPrice: "6500",
    },
    {
      SeatPriceId: 9,
      RoomId: 2,
      RowName: "C",
      SeatPrice: "7500",
    },
    {
      SeatPriceId: 10,
      RoomId: 2,
      RowName: "D",
      SeatPrice: "8500",
    },
    {
      SeatPriceId: 11,
      RoomId: 2,
      RowName: "E",
      SeatPrice: "9500",
    },
    {
      SeatPriceId: 12,
      RoomId: 2,
      RowName: "F",
      SeatPrice: "10500",
    },
    {
      SeatPriceId: 13,
      RoomId: 3,
      RowName: "A",
      SeatPrice: "6000",
    },

    {
      SeatPriceId: 14,
      RoomId: 3,
      RowName: "B",
      SeatPrice: "7000",
    },
    {
      SeatPriceId: 15,
      RoomId: 3,
      RowName: "C",
      SeatPrice: "8000",
    },
    {
      SeatPriceId: 16,
      RoomId: 3,
      RowName: "D",
      SeatPrice: "9000",
    },
    {
      SeatPriceId: 17,
      RoomId: 3,
      RowName: "E",
      SeatPrice: "10000",
    },
    {
      SeatPriceId: 18,
      RoomId: 3,
      RowName: "F",
      SeatPrice: "20000",
    },
    {
      SeatPriceId: 19,
      RoomId: 4,
      RowName: "A",
      SeatPrice: "6500",
    },

    {
      SeatPriceId: 20,
      RoomId: 4,
      RowName: "B",
      SeatPrice: "7500",
    },
    {
      SeatPriceId: 21,
      RoomId: 4,
      RowName: "C",
      SeatPrice: "9500",
    },
    {
      SeatPriceId: 22,
      RoomId: 4,
      RowName: "D",
      SeatPrice: "11500",
    },
    {
      SeatPriceId: 23,
      RoomId: 4,
      RowName: "E",
      SeatPrice: "12500",
    },
    {
      SeatPriceId: 24,
      RoomId: 4,
      RowName: "F",
      SeatPrice: "13500",
    },
  ],
};

export default data;
